apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-monitor

resources:
- https://github.com/gnunn1/gitops-catalog/grafana-operator/overlays/user-app
# github.com/redhat-cop/gitops-catalog/grafana-operator/overlays/user-app

# Patch in namespace for Argo CD that is managing this namespace
patches:
- patch: |-
    - op: add
      path: /spec/config/users
      value:
        default_theme: light
  target:
    kind: Grafana
    name: grafana
- patch: |-
    - op: add
      path: /subjects/0/namespace
      value: product-catalog-monitor
    - op: replace
      path: /metadata/name
      value: cluster-monitoring-view-product-catalog-monitor
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: cluster-monitoring-view
- patch: |-
    - op: add
      path: /subjects/0/namespace
      value: product-catalog-monitor
  target:
    group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: grafana-proxy
