apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts:
    namedCertificates:
    - names:
      - api.home.ocplab.com
      servingCertificate:
        name: openshift-api-certificate