apiVersion: operator.tekton.dev/v1alpha1
kind: TektonChain
metadata:
  name: chain
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetNamespace: openshift-pipelines