apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: s3-rhtpa
  namespace: openshift-storage
spec:
  secretName: s3-rhtpa
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - rhtpa.s3-openshift-storage.apps.hub.ocplab.com
