apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tenants-token
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            key: token
            name: tenants-token
