apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: credentials
  namespace: dev-tools
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: credentials
  data:
    - secretKey: password
      remoteRef:
        key: OLS_API_TOKEN
