resources:
- ns.yaml
- networkpolicy.yaml
- externalsecret.yaml
- operator-group.yaml
- subscription.yaml
- olsconfig.yaml
# no longer need the route now that Argo CD extension can use the service
# - route.yaml
