apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: rhtpa-storage
  namespace: trusted-profile-analyzer
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  bucketName: rhtpa
  generateBucketName: rhtpa
  objectBucketName: obc-trusted-profile-analyzer-rhtpa-storage
  storageClassName: noobaa.noobaa.io
