apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rhtpa-oidc
  namespace: trusted-profile-analyzer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: rhtpa-oidc
  data:
    - secretKey: clientSecret
      remoteRef:
        key: RHTPA_OIDC
