apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql
  namespace: trusted-profile-analyzer
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: postgresql
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: RHTPA_POSTGRESQL
