apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: collector-tls
  namespace: stackrox-secured-cluster-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: collector-tls
    creationPolicy: Owner
  data:
  - secretKey: ca.pem
    remoteRef:
      key: ACS_COLLECTOR_TLS_CA
  - secretKey: collector-cert.pem
    remoteRef:
      key: ACS_COLLECTOR_TLS_CERT
  - secretKey: collector-key.pem
    remoteRef:
      key: ACS_COLLECTOR_TLS_KEY
