apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: admission-control-tls
  namespace: stackrox-secured-cluster-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: admission-control-tls
    creationPolicy: Owner
  data:
  - secretKey: ca.pem
    remoteRef:
      key: ACS_ADMISSION_CONTROL_TLS_CA
  - secretKey: admission-control-cert.pem
    remoteRef:
      key: ACS_ADMISSION_CONTROL_TLS_CERT
  - secretKey: admission-control-key.pem
    remoteRef:
      key: ACS_ADMISSION_CONTROL_TLS_KEY
