kind: SecuredCluster
apiVersion: platform.stackrox.io/v1alpha1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: stackrox-secured-cluster-services
  namespace: stackrox-secured-cluster-service
spec:
  clusterName: ${CLUSTER_NAME}
  centralEndpoint: central-stackrox.apps.hub.ocplab.com:443
  admissionControl:
    contactImageScanners: ScanIfMissing
    listenOnCreates: true
    listenOnUpdates: true
    timeoutSeconds: 6
  scannerv4:
    db:
      persistence:
        persistentVolumeClaim:
          claimName: scanner-v4-db
    indexer:
      scaling:
        autoScaling: Enabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 3
    scannerComponent: Default
