resources:
- ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable-3.13'
    target:
      kind: Subscription
      name: container-security-operator
