apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: product-catalog
  labels:
    argocd.argoproj.io/project-inherit: global
spec:
  description: Product Catalog Team Project
  destinations:
  - namespace: 'product-catalog-dev'
    server: 'https://kubernetes.default.svc'
  - namespace: 'product-catalog-test'
    server: 'https://kubernetes.default.svc'
  - namespace: 'product-catalog-prod'
    server: 'https://kubernetes.default.svc'
  - namespace: 'product-catalog-cicd'
    server: 'https://kubernetes.default.svc'
  - namespace: 'product-catalog-monitor'
    server: 'https://kubernetes.default.svc'
  - namespace: 'product-catalog-gitops'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - '*'
  sourceNamespaces:
  - product-catalog-gitops
  roles:
    - description: Product Catalog Admins
      name: admin
      groups:
        - product-catalog-admins
      policies:
        - p, proj:product-catalog:admin, applications, *, product-catalog/*, allow
        - p, proj:product-catalog:admin, exec, create, product-catalog/*, allow
    - description: Product Catalog Users
      name: user
      groups:
        - product-catalog-users
      policies:
        - p, proj:product-catalog:user, applications, get, product-catalog/*, allow
        - p, proj:product-catalog:user, applications, sync, product-catalog/*, allow
    - description: Pipeline accounts
      name: pipeline
      groups:
        - product-catalog-pipeline
      policies:
        - p, proj:product-catalog:pipeline, applications, get, product-catalog/*, allow
        - p, proj:product-catalog:pipeline, applications, sync, product-catalog/*, allow
