resources:
- namespace.yaml

helmCharts:
- name: external-secrets
  version: v0.20.4
  repo: https://charts.external-secrets.io
  namespace: external-secrets
  releaseName: external-secrets

patches:
  - patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/securityContext/runAsUser
    target:
      kind: Deployment
