resources:
- namespace.yaml

helmCharts:
- name: external-secrets
  version: v0.20.4
  repo: https://charts.external-secrets.io
  namespace: external-secrets
  releaseName: external-secrets
  valuesFile: values.yaml
