apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: htpass-secret
  namespace: openshift-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: htpass-secret
  data:
    - secretKey: htpasswd
      remoteRef:
        key: HTPASSWD
