apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: oidc-info
  namespace: openshift-pipelines
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: oidc-info
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: OIDC_INFO
