apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    kubernetes.io/metadata.name: openshift-pipelines
    openshift.io/cluster-monitoring: "true"
    operator.tekton.dev/disable-proxy: "true"
  name: openshift-pipelines
