apiVersion: operator.openshift.io/v1alpha1
kind: ExternalSecrets
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: external-secrets-operator
  name: cluster
spec: {}
