apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/openshift-external-secrets-operator.external-secrets-operator: ""
  name: openshift-external-secrets-operator
  namespace: external-secrets-operator
spec:
  config:
    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  channel: tech-preview-v0.1
  installPlanApproval: Automatic
  name: openshift-external-secrets-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: external-secrets-operator.v0.1.0
