apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: product-catalog-gitops-rolebinding
  namespace: product-catalog-dev
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
  namespace: product-catalog-gitops
roleRef:
  kind: ClusterRole
  name: gitops-manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: product-catalog-gitops-rolebinding
  namespace: product-catalog-test
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
  namespace: product-catalog-gitops
roleRef:
  kind: ClusterRole
  name: gitops-manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: product-catalog-gitops-rolebinding
  namespace: product-catalog-prod
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
  namespace: product-catalog-gitops
roleRef:
  kind: ClusterRole
  name: gitops-manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: product-catalog-gitops-rolebinding
  namespace: product-catalog-cicd
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
  namespace: product-catalog-gitops
roleRef:
  kind: ClusterRole
  name: gitops-manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: product-catalog-gitops-rolebinding
  namespace: product-catalog-monitor
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
  namespace: product-catalog-gitops
roleRef:
  kind: ClusterRole
  name: gitops-manager-role
  apiGroup: rbac.authorization.k8s.io