apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ldap-secret
  namespace: openshift-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: ldap-secret
  data:
    - secretKey: bindPassword
      remoteRef:
        key: LDAP
