apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc-client-secret
  namespace: openshift-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: oidc-client-secret
  data:
    - secretKey: clientSecret
      remoteRef:
        key: OIDC_OCPLAB
