apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openshift-wildcard
  namespace: openshift-ingress
spec:
  secretName: openshift-wildcard-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: '*.apps.replace.me'
  dnsNames:
  - '*.apps.replace.me'