apiVersion: v1
kind: ServiceAccount
metadata:
  name: read-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-secrets
subjects:
  - kind: ServiceAccount
    name: read-secrets
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: k8s-store
spec:
  provider:
    kubernetes:
      remoteNamespace: gitops
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: read-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bearer-token
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: k8s-store
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      mergePolicy: Merge
      engineVersion: v2
      data:
        lightspeed.auth.header: "Bearer {{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: lightspeed-auth-secret
        property: token
