apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: doppler-push-secret
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: eso-token-cluster-push-secret
            key: dopplerToken
            namespace: hub-secrets
