apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: product-catalog-users-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: product-catalog-users
