apiVersion: operator.tekton.dev/v1alpha1
kind: TektonHub
metadata:
  name: hub
spec:
  targetNamespace: openshift-pipelines

  catalogs:
    - name: local
      org: gnunn-gitops
      type: community
      provider: github
      url: https://github.com/gnunn-gitops/tekton-catalog
      revision: main

  api:
    catalogRefreshInterval: 5m
