namespace: trusted-profile-analyzer

helmCharts:
- name: redhat-trusted-profile-analyzer
  version: 1.1.0
  repo: https://charts.openshift.io/
  valuesFile: values.yaml
  namespace: trusted-profile-analyzer
  releaseName: rhtpa
