namespace: trusted-profile-analyzer

helmCharts:
- name: redhat-trusted-profile-analyzer
  version: 1.0.0
  repo: https://charts.openshift.io/
  valuesFile: values.yaml
  namespace: trusted-profile-analyzer
  releaseName: rhtpa

resources:
- namespace.yaml
- obc.yaml
- postgresql-es.yaml
- postgresql.yaml

patches:
  - patch: |
      - op: add
        path: /metadata/labels/argocd.argoproj.io~1sync-wave
        value: "5"
    target:
      kind: Deployment
      name: importer
