apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: kyverno
  namespace: kyverno-policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: policies, operator: In, values: ["kyverno"]}