apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhtas-operator
spec:
  config:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 5m
        memory: 128Mi
  channel: stable-v1.1
  installPlanApproval: Automatic
  name: rhtas-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
