apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-workaround993-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-workaround993-rolebinding
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
roleRef:
  kind: Role
  name: argocd-workaround993-role
  apiGroup: rbac.authorization.k8s.io