apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: rhtpa-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: rhtpa-oidc
  data:
    - secretKey: clientSecret
      remoteRef:
        key: RHTPA_OIDC
