apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  enableCephTools: false
  multiCloudGateway:
    dbStorageClassName: lvms-vg1
    reconcileStrategy: standalone
  nfs:
    enable: false
    
