apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '1'
  labels:
    gitops.ownedBy: cluster-config
  name: sealed-secrets
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/apps/sealed-secrets-operator/overlays/default
    repoURL: https://github.com/gnunn-gitops/cluster-config.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
