apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-shared-cluster-access
rules:
- apiGroups:
    - argoproj.io
  resources:
    - applications
    - applicationsets
    - appprojects
    - rolloutmanagers
    - rollouts
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - authorization.k8s.io
  resources:
    - SelfSubjectAccessReview
  verbs:
    - list
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  - serviceaccounts
  - services
  - services/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - bindings
  - events
  - limitranges
  - namespaces/status
  - pods/log
  - pods/status
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  - daemonsets
  - daemonsets/status
  - deployments
  - deployments/scale
  - deployments/status
  - replicasets
  - replicasets/scale
  - replicasets/status
  - statefulsets
  - statefulsets/scale
  - statefulsets/status
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-shared-cluster-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-shared-cluster-access
subjects:
  - kind: ServiceAccount
    name: argocd-argocd-application-controller
    namespace: gitops
  - kind: ServiceAccount
    name: argocd-argocd-server
    namespace: gitops
  - kind: ServiceAccount
    name: argocd-applicationset-controller
    namespace: gitops
