apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: argocd-unhealthy-alert
  annotations:
    policy.open-cluster-management.io/disable-templates: "true"
spec:
  groups:
  - name: ArgoCD
    rules:
    - alert: ArgoCDHealthAlert
      annotations:
        message: ArgoCD application {{ $labels.name }} is not healthy
      expr: argocd_app_info{namespace="openshift-gitops", health_status!~"Healthy|Suspended|Progressing|Degraded"} > 0
      for: 5m
      labels:
        severity: warning
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: argocd-degraded-alert
  annotations:
    policy.open-cluster-management.io/disable-templates: "true"
spec:
  groups:
  - name: ArgoCD
    rules:
    - alert: ArgoCDDegradedAlert
      annotations:
        message: ArgoCD application {{ $labels.name }} is degraded
      expr: argocd_app_info{namespace="openshift-gitops", health_status="Degraded"} > 0
      for: 5m
      labels:
        severity: critical
