apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Validate=false,ServerSideApply=true
spec:
  servingCerts:
    namedCertificates:
    - names:
      - api.${BASE_DOMAIN}
      servingCertificate:
        name: openshift-api-certificate
