tenant: rollouts-demo

default:
  argocd:
    cluster:
      name: in-cluster
  labels:
    argocd.argoproj.io/managed-by: gitops
    tenant: rollouts-demo
  networkPolicy: true
  rbac:
    adminGroups:
      - rollouts-demo-admins
    editGroups:
      - rollouts-demo-users

argocd:
  namespace: gitops
  sourceRepos:
    - '*'
  adminGroups:
    - rollouts-demo-admins
  userGroups:
    - rollouts-demo-users
  pipelineGroups:
    - rollouts-demo-pipeline

externalSecrets:
  tenantClusterSecretStore: doppler-cluster
  tenantSecretNamespace: tenant-secrets

namespaces:

  dev:
    annotations:
      openshift.io/description: Project for dev environment of rollouts demo application
      openshift.io/display-name: Rollouts Demo Development

  prod:
    annotations:
      openshift.io/description: Project for prod environment of rollouts demo application
      openshift.io/display-name: Rollouts Demo Production

  cicd:
    externalSecrets:
      tenantTokenKey: TENANT_ROLLOUTS_DEMO_DOPPLER_TOKEN
    annotations:
      openshift.io/description: Project for ci/cd tools for rollouts demo application
      openshift.io/display-name: Rollouts Demo CI/CD

  gitops:
    annotations:
      openshift.io/description: Project for gitops tool for rollouts demo team
      openshift.io/display-name: Rollouts Demo GitOps
